version: "3.8"
services:
    backend_sample:
        container_name: backend_sample_container
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        ports:
            - 3000:3000
        env_file:
            - ./src/configs/.env.development # Ensure .env.development has the AWS credentials
        environment:
            - DOCKER_ENV=true
            - COGNITO_USER_POOL_ID=us-west-2_mOnfhzlwA
            - COGNITO_CLIENT_ID=60u3ht4t17mlqp52d9vmuseh5t
            - COGNITO_REGION=us-west-2
            - COGNITO_CLIENT_SECRET=dm97dgknbl22m3trukqatn698ks0pktrher0iflia62pk49m6s3
        volumes:
            - ./src:/app/src
        depends_on:
            - mongodb
    mongodb:
        container_name: mongodb_container
        image: mongo:latest
        restart: always
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: Sophorn
            MONGO_INITDB_ROOT_PASSWORD: 123123
            MONGO_INITDB_DATABASE: my_authService
volumes:
    mongodb_data:
